### ISSUE TITLE
mpv on top of taskbar (dark mode attempt)

### ISSUE THREAD

**Issue by eltrevii** [willnode/autobloom#18]
i was about to implement dark mode but the mpv window appears on top of the taskbar (dark mode only), do you know how to fix it? (check [my repo](/aritz331/autobloom) for the updated version w/ dark mode)

**Comment by willnode** [comment]
Hi, I'll get back to you when I got my hands on Windows laptop. (won't be that long).

**Comment by eltrevii** [comment]
do you have your laptop now?

**Comment by eltrevii** [comment]
@willnode hello?

**Comment by willnode** [comment]
Sorry, actually I have tried it and found the problem might be in the video.  It's highly compressed. Maybe some players wouldn't be able to play it properly.

Also, I know the video origin, but long time ago I decided not to add it here because it's "low quality". There are so many things needed to take in consideration to match the quality of original video of Microsoft's Bloom.

**Comment by eltrevii** [comment]
ok, then ill remove the dark mode option
